skip_clone: true
when:
- branch: master
  event: push
steps:
  - name: github-pages
    image: alpine/git
    environment:
      GITEA_USER:
        from_secret: GITEA_USER
      GITEA_PASSWORD:
        from_secret: GITEA_PASSWORD
      GITHUB_USER:
        from_secret: GITHUB_USER
      GITHUB_PASSWORD:
        from_secret: GITHUB_PASSWORD
      GITHUB_EMAIL:
        from_secret: GITHUB_EMAIL
    commands:
      - git config --global http.sslVerify false
      - git clone -b master https://$GITEA_USER:$GITEA_PASSWORD@pre.gitea.com/marti/marti-march-website.git
      - git clone -b master https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/MartiMarch/marti-march-website.git marti-march-website-gh
      - rm -rf marti-march-website/.git
      - cp -r marti-march-website/. marti-march-website-gh/
      - ls -ll marti-march-website-gh
      - cd marti-march-website-gh
      - git config --global user.email $GITHUB_EMAIL
      - git config --global user.name $GITHUB_USER
      - git add .
      - git status
      - git commit -m 'sync from Gitea' || true
      - git remote remove origin
      - git remote add origin https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/MartiMarch/marti-march-website.git
      - git push origin master
